service: authentication-serveless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /auth
          method: post
          request:
              schemas:
                application/json: ${file(./schemas/auth.json)}
plugins:
  - serverless-offline


# org: hiagofss
# app: auth-function